version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    image: fernandorojo72/crowdsourcedgeoguessr_server
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    image: fernandorojo72/crowdsourcedgeoguessr_client
    environment:
      SERVER_URL: server
      TEST: "hello"
